services:
  mysql:
    image: mysql:8.0
    container_name: farmlokal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: farmlokal
      MYSQL_USER: farmlokal_user
      MYSQL_PASSWORD: farmlokal_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./prisma/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - farmlokal-network

  redis:
    image: redis:7-alpine
    container_name: farmlokal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - farmlokal-network

volumes:
  mysql_data:
  redis_data:


networks:
  farmlokal-network:
    driver: bridge
